os: osx
osx_image: xcode11.3.1
language: swift

env:
  matrix:
    - TEST_SDK=iphonesimulator13.2 OS=13.2 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator13.2 OS=13.2 NAME='iPhone 11'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project SwiftyLib.xcodeproj -scheme SwiftyLib -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES

